variables:
  MYSQL_DATABASE: supertestdb
  MYSQL_USER: root
  MYSQL_ROOT_PASSWORD: secret

test:
  image: node:latest
  services:
    - mysql:5
  script:
    - npm install -g flow-bin
    - cd server && npm install && npm test && rm node_modules/bcryptjs/src/bower.json && flow check src
    - cd ../client && npm install && npm test && flow check src